import { DashboardAuthProvider } from "@/context/DashboardAuthContext"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function DashBoardLayout({
  children,
}: {
  children : React.ReactNode
}) {
  return (
    <DashboardAuthProvider>
      {children}
    </DashboardAuthProvider>
  )
}