services:
  # --- Backend Service (Express) ---
  backend:
    build:
      context: ./Backend/stayhub-be
      dockerfile: Dockerfile
    container_name: stayhub-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - SESSION_KEY=st@yI-IubBNVTHVADu~ng
      - FRONTEND_URL=http://localhost:3000
      - DB_HOST=aws-1-ap-southeast-2.pooler.supabase.com
      - DB_USER=postgres.yijwpmeackjqszmdyrpa
      - DB_PASSWORD=xWWlpaAj1%25%23pS7
      - DB_NAME=postgres
      - DB_PORT=5432
      - EMAIL_USER=stayhub.project@gmail.com
      - EMAIL_PASS=whnofpvuvcswsvkw
      # Optional: Add MinIO configs here so your backend can connect
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=admin
      - S3_SECRET_KEY=password
      - S3_BUCKET_NAME=stayhub-uploads
    volumes:
      - ./Backend/stayhub-be:/app
      - /app/node_modules
    networks:
      - stayhub-network

  # --- Frontend Service (Next.js) ---
  frontend:
    build:
      context: ./Frontend/stayhub-fe
      dockerfile: Dockerfile
    container_name: stayhub-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - WATCHPACK_POLLING=true
    volumes:
      - ./Frontend/stayhub-fe:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - stayhub-network

networks:
  stayhub-network:
    driver: bridge