CREATE TABLE IF NOT EXISTS session (
  sid varchar NOT NULL COLLATE "default",
  sess json NOT NULL,
  expire timestamp(6) NOT NULL,
  CONSTRAINT session_pkey PRIMARY KEY (sid) NOT DEFERRABLE INITIALLY IMMEDIATE
) WITH (OIDS = FALSE);
CREATE INDEX IF NOT EXISTS IDX_session_expire ON session USING BTREE (expire);

CREATE table if not exists passwordResetTokens (
  email VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL PRIMARY KEY,
  expiresAt TIMESTAMP NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS accounts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(100) UNIQUE NOT NULL,
  salt bytea NOT NULL,
  hash bytea NOT NULL,
  email varchar(100) UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  accountID int UNIQUE NOT NULL,
  firstName varchar(100) NOT NULL,
  lastName varchar(100),
  phoneNumber varchar(11),
  gender varchar(10) NOT NULL DEFAULT 'None',
  birthDate date,
  countryCode char(2) NOT NULL DEFAULT 'UN',
  address varchar(256),
  avatar text
);
CREATE TABLE IF NOT EXISTS reserves (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userID int UNIQUE NOT NULL,
  roomID int UNIQUE NOT NULL,
  created_at timestamp NOT NULL DEFAULT (now()),
  checkinDate date NOT NULL,
  checkoutDate date NOT NULL
);
CREATE TABLE IF NOT EXISTS reviews (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userID int UNIQUE NOT NULL,
  roomID int UNIQUE NOT NULL,
  created_at timestamp NOT NULL DEFAULT (now()),
  rating INT NOT NULL DEFAULT 0 CHECK (
    rating >= 0
    AND rating <= 5
  ),
  description text NOT NULL,
  pros text,
  cons text,
  like_count int,
  response text
);
CREATE TABLE IF NOT EXISTS amenities (
  name varchar(100) PRIMARY KEY,
  icon text NOT NULL,
  category varchar(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS policies (
  name varchar(100) PRIMARY KEY,
  description text NOT NULL
);
CREATE TABLE IF NOT EXISTS hotels (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  classification INT NOT NULL DEFAULT 0 CHECK (
    classification >= 0
    AND classification <= 5
  ),
  location varchar(255) NOT NULL,
  description text,
  amenities amenities [],
  policies policies [],
  previewImages text []
);
CREATE TABLE IF NOT EXISTS beds (
  name varchar(100) PRIMARY KEY,
  count int NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS rooms (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotelID int UNIQUE NOT NULL,
  amenities amenities [],
  price int NOT NULL,
  size int NOT NULL,
  type text NOT NULL,
  beds beds [],
  capacity int NOT NULL DEFAULT 1,
  discount decimal NOT NULL DEFAULT 0,
  previewImages text []
);
CREATE TABLE IF NOT EXISTS booking (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roomID int UNIQUE NOT NULL,
  firstName varchar(100) NOT NULL,
  lastName varchar(100),
  phone varchar(11) NOT NULL,
  checkinDate date NOT NULL DEFAULT (CURRENT_DATE),
  checkoutDate date NOT NULL DEFAULT (CURRENT_DATE + 5)
);
CREATE TABLE IF NOT EXISTS roles (
  employeeID int,
  role varchar(100),
  PRIMARY KEY (employeeID, role)
);
CREATE TABLE IF NOT EXISTS employees (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  accountID int UNIQUE NOT NULL,
  firstName varchar(100) NOT NULL,
  lastName varchar(100),
  salary int NOT NULL
);
CREATE TABLE IF NOT EXISTS shifts (
  employeeID int,
  day date DEFAULT (CURRENT_DATE),
  startTime time NOT NULL,
  endTime time NOT NULL,
  PRIMARY KEY (employeeID, day)
);
CREATE TABLE IF NOT EXISTS services (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(100) NOT NULL,
  name varchar(100) NOT NULL,
  description text,
  coverImage text,
  price int NOT NULL DEFAULT 0,
  quantity int NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS works (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employeeID int UNIQUE NOT NULL,
  serviceID int UNIQUE NOT NULL,
  startTime timestamp NOT NULL,
  endTime timestamp NOT NULL
);
ALTER TABLE IF EXISTS users
ADD CONSTRAINT fk_accountID FOREIGN KEY (accountID) REFERENCES accounts (id);
CREATE TABLE IF NOT EXISTS users_reserves (
  users_id int,
  reserves_userID int,
  PRIMARY KEY (users_id, reserves_userID)
);
ALTER TABLE IF EXISTS users_reserves
ADD CONSTRAINT fk_users_id FOREIGN KEY (users_id) REFERENCES users (id);
ALTER TABLE IF EXISTS users_reserves
ADD CONSTRAINT fk_reserves_userID FOREIGN KEY (reserves_userID) REFERENCES reserves (userID);
CREATE TABLE IF NOT EXISTS rooms_reserves (
  rooms_id int,
  reserves_roomID int,
  PRIMARY KEY (rooms_id, reserves_roomID)
);
ALTER TABLE IF EXISTS rooms_reserves
ADD CONSTRAINT fk_rooms_id FOREIGN KEY (rooms_id) REFERENCES rooms (id);
ALTER TABLE IF EXISTS rooms_reserves
ADD CONSTRAINT fk_reserves_roomID FOREIGN KEY (reserves_roomID) REFERENCES reserves (roomID);
CREATE TABLE IF NOT EXISTS users_reviews (
  users_id int,
  reviews_userID int,
  PRIMARY KEY (users_id, reviews_userID)
);
ALTER TABLE IF EXISTS users_reviews
ADD CONSTRAINT fk_users_id FOREIGN KEY (users_id) REFERENCES users (id);
ALTER TABLE IF EXISTS users_reviews
ADD CONSTRAINT fk_reviews_userID FOREIGN KEY (reviews_userID) REFERENCES reviews (userID);
CREATE TABLE IF NOT EXISTS rooms_reviews (
  rooms_id int,
  reviews_roomID int,
  PRIMARY KEY (rooms_id, reviews_roomID)
);
ALTER TABLE IF EXISTS rooms_reviews
ADD CONSTRAINT fk_rooms_id FOREIGN KEY (rooms_id) REFERENCES rooms (id);
ALTER TABLE IF EXISTS rooms_reviews
ADD CONSTRAINT fk_reviews_roomID FOREIGN KEY (reviews_roomID) REFERENCES reviews (roomID);
ALTER TABLE IF EXISTS rooms
ADD CONSTRAINT fk_hotelID FOREIGN KEY (hotelID) REFERENCES hotels (id);
ALTER TABLE IF EXISTS booking
ADD CONSTRAINT fk_roomID FOREIGN KEY (roomID) REFERENCES rooms (id);
ALTER TABLE IF EXISTS employees
ADD CONSTRAINT fk_accountID FOREIGN KEY (accountID) REFERENCES accounts (id);
ALTER TABLE IF EXISTS shifts
ADD CONSTRAINT fk_employeeID FOREIGN KEY (employeeID) REFERENCES employees (id);
ALTER TABLE IF EXISTS works
ADD CONSTRAINT fk_employeeID FOREIGN KEY (employeeID) REFERENCES employees (id);
ALTER TABLE IF EXISTS works
ADD CONSTRAINT fk_serviceID FOREIGN KEY (serviceID) REFERENCES services (id);


CREATE TABLE IF NOT EXISTS destinations(
  id int GENERATED by default as IDENTITY PRIMARY key,
  name varchar(100) not null,
  price int not null default 0,
  image text not null,
  description text,
  category varchar(50) not null
)

INSERT INTO destinations (name, price, image, description, category) VALUES
('Paris, France', 128, '/images/paris.jpg', 'Romantic escapes, art, and cafés.', 'spring'),
('Kyoto, Japan', 190, '/images/kyoto.jpg', 'Cherry blossoms and temples.', 'spring'),
('Santorini, Greece', 225, '/images/santorini.jpg', 'Sunsets, sea views, and serenity.', 'summer'),
('Bali, Indonesia', 26, '/images/bali.jpg', 'Beaches, nature, and calm vibes.', 'summer'),
('Tuscany, Italy', 160, '/images/tuscany.jpg', 'Vineyards and golden hills.', 'autumn'),
('Swiss Alps', 300, '/images/swiss.jpg', 'Skiing and snowy mountains.', 'winter'),

('Paris, France', 128, '/images/Product-card-1.jpg', 'Romantic escapes, art, and cafés.', 'spring'),
('Santorini, Greece', 225, '/images/Product-card-1.jpg', 'Sunsets, sea views, and serenity.', 'spring'),
('Bali, Indonesia', 26, '/images/Product-card-1.jpg', 'Beaches, nature, and calm vibes.', 'spring'),
('Kyoto, Japan', 190, '/images/Product-card-1.jpg', 'Cherry blossoms and temples.', 'spring'),

('Barcelona, Spain', 110, '/images/Product-card-1.jpg', 'Urban beaches and tapas nights.', 'summer'),
('Mykonos, Greece', 128, '/images/Product-card-1.jpg', 'Whitewashed alleys and seaside fun.', 'summer'),
('Nice, France', 128, '/images/Product-card-1.jpg', 'Pebbled beaches and coastal charm.', 'summer'),
('Amalfi Coast, Italy', 128, '/images/Product-card-1.jpg', 'Cliffside villas and lemon groves.', 'summer'),

('Tuscany, Italy', 160, '/images/Product-card-1.jpg', 'Vineyards, golden hills, and rustic villas.', 'autumn'),
('Prague, Czech', 189, '/images/Product-card-1.jpg', 'Cobblestone walks and cozy cafés.', 'autumn'),
('Seoul, South Korea', 105, '/images/Product-card-1.jpg', 'Autumn foliage and street food.', 'autumn'),
('Munich, Germany', 115, '/images/Product-card-1.jpg', 'Oktoberfest and beer gardens.', 'autumn'),

('Reykjavik, Iceland', 128, '/images/Product-card-1.jpg', 'Auroras, hot springs, and winter wonders.', 'winter'),
('Vienna, Austria', 128, '/images/Product-card-1.jpg', 'Christmas markets and snowy strolls.', 'winter'),
('Quebec City, Canada', 128, '/images/Product-card-1.jpg', 'Snowy magic, castles, and French flair.', 'winter'),
('Lucerne, Switzerland', 128, '/images/Product-card-1.jpg', 'Lakes, mountains, and old-town charm.', 'winter');

