
-- ==========================================
-- 1. Table Creations (Unchanged)
-- ==========================================

CREATE TABLE IF NOT EXISTS user_session (
  sid varchar NOT NULL COLLATE "default",
  sess json NOT NULL,
  expire timestamp(6) NOT NULL,
  CONSTRAINT user_session_pkey PRIMARY KEY (sid) NOT DEFERRABLE INITIALLY IMMEDIATE
) WITH (OIDS = FALSE);

CREATE INDEX IF NOT EXISTS IDX_user_session_expire ON user_session USING BTREE (expire);

CREATE TABLE IF NOT EXISTS employee_session (
  sid varchar NOT NULL COLLATE "default",
  sess json NOT NULL,
  expire timestamp(6) NOT NULL,
  CONSTRAINT employee_session_pkey PRIMARY KEY (sid) NOT DEFERRABLE INITIALLY IMMEDIATE
) WITH (OIDS = FALSE);

CREATE INDEX IF NOT EXISTS IDX_employee_session_expire ON employee_session USING BTREE (expire);


CREATE table if not exists passwordResetTokens (
  email VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL PRIMARY KEY,
  expiresAt TIMESTAMP NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(100) UNIQUE NOT NULL,
  salt bytea NOT NULL,
  hash bytea NOT NULL,
  email varchar(100) UNIQUE NOT NULL,
  firstName varchar(100) NOT NULL,
  lastName varchar(100),
  phoneNumber varchar(11),
  gender varchar(10) NOT NULL DEFAULT 'None',
  birthDate date,
  countryCode char(2) NOT NULL DEFAULT 'UN',
  address varchar(256),
  avatar text
);

CREATE TABLE IF NOT EXISTS employees (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(100) UNIQUE NOT NULL,
  salt bytea NOT NULL,
  hash bytea NOT NULL,
  email varchar(100) UNIQUE NOT NULL,
  role varchar(100),
  branchID int,
  hotelID int,
  firstName varchar(100) NOT NULL,
  lastName varchar(100),
  salary int NOT NULL,
  createdAt timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS reserves (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userID int UNIQUE NOT NULL,
  roomID int UNIQUE NOT NULL,
  created_at timestamp NOT NULL DEFAULT (now()),
  checkinDate date NOT NULL,
  checkoutDate date NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userID int UNIQUE NOT NULL,
  roomID int UNIQUE NOT NULL,
  created_at timestamp NOT NULL DEFAULT (now()),
  rating INT NOT NULL DEFAULT 0 CHECK (
    rating >= 0
    AND rating <= 5
  ),
  description text NOT NULL,
  pros text,
  cons text,
  like_count int,
  response text
);

CREATE TABLE IF NOT EXISTS amenities (
  name varchar(100) PRIMARY KEY,
  icon text NOT NULL,
  category varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS policies (
  name varchar(100) PRIMARY KEY,
  description text NOT NULL
);

CREATE TABLE IF NOT EXISTS hotels (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  classification INT NOT NULL DEFAULT 0 CHECK (
    classification >= 0
    AND classification <= 5
  ),
  branchID int,
  location varchar(255) NOT NULL,
  description text,
  amenities amenities [],
  policies policies [],
  previewImages text [],
  contact_email varchar(100),
  contact_phone varchar(20),
  salt bytea,
  hash bytea
);

CREATE TABLE IF NOT EXISTS branch (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  location varchar(255) NOT NULL,
  description text
);

CREATE TABLE IF NOT EXISTS beds (
  name varchar(100) PRIMARY KEY,
  count int NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS rooms (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotelID int UNIQUE NOT NULL,
  amenities amenities [],
  price int NOT NULL,
  size int NOT NULL,
  type text NOT NULL,
  beds beds [],
  capacity int NOT NULL DEFAULT 1,
  discount decimal NOT NULL DEFAULT 0,
  previewImages text [],
  description text
);

CREATE TABLE IF NOT EXISTS booking (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roomID int UNIQUE NOT NULL,
  firstName varchar(100) NOT NULL,
  lastName varchar(100),
  phone varchar(11) NOT NULL,
  checkinDate date NOT NULL DEFAULT (CURRENT_DATE),
  checkoutDate date NOT NULL DEFAULT (CURRENT_DATE + 5)
);

CREATE TABLE IF NOT EXISTS roles (
  name varchar(100) NOT NULL PRIMARY KEY,
  tier int NOT NULL
);



CREATE TABLE IF NOT EXISTS shifts (
  employeeID int,
  day date DEFAULT (CURRENT_DATE),
  startTime time NOT NULL,
  endTime time NOT NULL,
  PRIMARY KEY (employeeID, day)
);

CREATE TABLE IF NOT EXISTS services (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(100) NOT NULL,
  name varchar(100) NOT NULL,
  description text,
  coverImage text,
  price int NOT NULL DEFAULT 0,
  quantity int NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS works (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employeeID int UNIQUE NOT NULL,
  serviceID int UNIQUE NOT NULL,
  startTime timestamp NOT NULL,
  endTime timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS deals (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  location VARCHAR(150) NOT NULL,
  image TEXT NOT NULL,
  rating DECIMAL(2, 1),
  review_count INT,
  price_original INT,
  price_discount INT,
  tag TEXT DEFAULT 'Getaway Deal'
);

CREATE TABLE IF NOT EXISTS top_sights (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  flag_icon VARCHAR(10) NOT NULL,
  image TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS things_to_do (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  image TEXT NOT NULL,
  category VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS destinations(
  id int GENERATED by default as IDENTITY PRIMARY key,
  name varchar(100) not null,
  price int not null default 0,
  image text not null,
  description text,
  category varchar(50) not null
);

CREATE TABLE IF NOT EXISTS home_Guests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  location VARCHAR(150) NOT NULL,
  image TEXT NOT NULL,
  rating DECIMAL(2, 1),
  review_count INT,
  price_original INT
);


CREATE TABLE IF NOT EXISTS users_reserves (
  users_id int,
  reserves_userID int,
  PRIMARY KEY (users_id, reserves_userID)
);

CREATE TABLE IF NOT EXISTS rooms_reserves (
  rooms_id int,
  reserves_roomID int,
  PRIMARY KEY (rooms_id, reserves_roomID)
);

CREATE TABLE IF NOT EXISTS users_reviews (
  users_id int,
  reviews_userID int,
  PRIMARY KEY (users_id, reviews_userID)
);

CREATE TABLE IF NOT EXISTS rooms_reviews (
  rooms_id int,
  reviews_roomID int,
  PRIMARY KEY (rooms_id, reviews_roomID)
);

CREATE TABLE IF NOT EXISTS employee_roles (
  employeeID int,
  role varchar(100),
  PRIMARY KEY (employeeID, role)
);

-- ==========================================
-- 2. Alter Tables (Rewritten with DO Blocks)
-- ==========================================

DO $$ 
BEGIN 
    ALTER TABLE hotels ADD COLUMN IF NOT EXISTS contact_email varchar(100);
    ALTER TABLE hotels ADD COLUMN IF NOT EXISTS contact_phone varchar(20);
    ALTER TABLE hotels ADD COLUMN IF NOT EXISTS salt bytea;
    ALTER TABLE hotels ADD COLUMN IF NOT EXISTS hash bytea;
END $$;


-- 3. Link Users_Reserves -> Users
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_id' AND conrelid = 'users_reserves'::regclass) THEN 
        ALTER TABLE users_reserves ADD CONSTRAINT fk_users_id FOREIGN KEY (users_id) REFERENCES users (id);
    END IF; 
END $$;

-- 4. Link Users_Reserves -> Reserves
DO $$ 
BEGIN 
    -- FIXED: 'fk_reserves_userid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_reserves_userid' AND conrelid = 'users_reserves'::regclass) THEN 
        ALTER TABLE users_reserves ADD CONSTRAINT fk_reserves_userID FOREIGN KEY (reserves_userID) REFERENCES reserves (userID);
    END IF; 
END $$;

-- 5. Link Rooms_Reserves -> Rooms
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rooms_id' AND conrelid = 'rooms_reserves'::regclass) THEN 
        ALTER TABLE rooms_reserves ADD CONSTRAINT fk_rooms_id FOREIGN KEY (rooms_id) REFERENCES rooms (id);
    END IF; 
END $$;

-- 6. Link Rooms_Reserves -> Reserves
DO $$ 
BEGIN 
    -- FIXED: 'fk_reserves_roomid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_reserves_roomid' AND conrelid = 'rooms_reserves'::regclass) THEN 
        ALTER TABLE rooms_reserves ADD CONSTRAINT fk_reserves_roomID FOREIGN KEY (reserves_roomID) REFERENCES reserves (roomID);
    END IF; 
END $$;

-- 7. Link Users_Reviews -> Users
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_id' AND conrelid = 'users_reviews'::regclass) THEN 
        ALTER TABLE users_reviews ADD CONSTRAINT fk_users_id FOREIGN KEY (users_id) REFERENCES users (id);
    END IF; 
END $$;

-- 8. Link Users_Reviews -> Reviews
DO $$ 
BEGIN 
    -- FIXED: 'fk_reviews_userid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_reviews_userid' AND conrelid = 'users_reviews'::regclass) THEN 
        ALTER TABLE users_reviews ADD CONSTRAINT fk_reviews_userID FOREIGN KEY (reviews_userID) REFERENCES reviews (userID);
    END IF; 
END $$;

-- 9. Link Rooms_Reviews -> Rooms
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rooms_id' AND conrelid = 'rooms_reviews'::regclass) THEN 
        ALTER TABLE rooms_reviews ADD CONSTRAINT fk_rooms_id FOREIGN KEY (rooms_id) REFERENCES rooms (id);
    END IF; 
END $$;

-- 10. Link Rooms_Reviews -> Reviews
DO $$ 
BEGIN 
    -- FIXED: 'fk_reviews_roomid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_reviews_roomid' AND conrelid = 'rooms_reviews'::regclass) THEN 
        ALTER TABLE rooms_reviews ADD CONSTRAINT fk_reviews_roomID FOREIGN KEY (reviews_roomID) REFERENCES reviews (roomID);
    END IF; 
END $$;

-- 11. Link Rooms -> Hotels
DO $$ 
BEGIN 
    -- FIXED: 'fk_hotelid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_hotelid' AND conrelid = 'rooms'::regclass) THEN 
        ALTER TABLE rooms ADD CONSTRAINT fk_hotelID FOREIGN KEY (hotelID) REFERENCES hotels (id);
    END IF; 
END $$;

-- 12. Link Booking -> Rooms
DO $$ 
BEGIN 
    -- FIXED: 'fk_roomid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_roomid' AND conrelid = 'booking'::regclass) THEN 
        ALTER TABLE booking ADD CONSTRAINT fk_roomID FOREIGN KEY (roomID) REFERENCES rooms (id);
    END IF; 
END $$;


-- 14. Link Shifts -> Employees
DO $$ 
BEGIN 
    -- FIXED: 'fk_employeeid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_employeeid' AND conrelid = 'shifts'::regclass) THEN 
        ALTER TABLE shifts ADD CONSTRAINT fk_employeeID FOREIGN KEY (employeeID) REFERENCES employees (id);
    END IF; 
END $$;

-- 15. Link Works -> Employees
DO $$ 
BEGIN 
    -- FIXED: 'fk_employeeid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_employeeid' AND conrelid = 'works'::regclass) THEN 
        ALTER TABLE works ADD CONSTRAINT fk_employeeID FOREIGN KEY (employeeID) REFERENCES employees (id);
    END IF; 
END $$;

-- 16. Link Works -> Services
DO $$ 
BEGIN 
    -- FIXED: 'fk_serviceid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_serviceid' AND conrelid = 'works'::regclass) THEN 
        ALTER TABLE works ADD CONSTRAINT fk_serviceID FOREIGN KEY (serviceID) REFERENCES services (id);
    END IF; 
END $$;

-- 17. Link Employees -> Hotels
DO $$ 
BEGIN 
    -- FIXED: 'fk_hotelid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_hotelid' AND conrelid = 'employees'::regclass) THEN 
        ALTER TABLE employees ADD CONSTRAINT fk_hotelid FOREIGN KEY (hotelid) REFERENCES hotels (id);
    END IF; 
END $$;

-- 18. Link Employee -> Roles
DO $$ 
BEGIN 
    -- FIXED: 'fk_employee_roles'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_employee_roles' AND conrelid = 'employee_roles'::regclass) THEN 
        ALTER TABLE employee_roles ADD CONSTRAINT fk_employee_roles FOREIGN KEY (role) REFERENCES roles (name);
    END IF; 
END $$;

-- Link Employees -> Role
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_employees_role' AND conrelid = 'employees'::regclass) THEN 
        ALTER TABLE employees ADD CONSTRAINT fk_employees_role FOREIGN KEY (role) REFERENCES roles (name);
    END IF; 
END $$;

-- Link Employees -> Branch
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_employees_branchid' AND conrelid = 'employees'::regclass) THEN 
        ALTER TABLE employees ADD CONSTRAINT fk_employees_branchid FOREIGN KEY (branchID) REFERENCES branch (id);
    END IF; 
END $$;

-- Link Hotels -> Branch
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_hotels_branchid' AND conrelid = 'hotels'::regclass) THEN 
        ALTER TABLE hotels ADD CONSTRAINT fk_hotels_branchid FOREIGN KEY (branchID) REFERENCES branch (id);
    END IF; 
END $$;



CREATE TABLE IF NOT EXISTS destinations(
  id int GENERATED by default as IDENTITY PRIMARY key,
  name varchar(100) not null,
  price int not null default 0,
  image text not null,
  description text,
  category varchar(50) not null
);

DO $$ 
BEGIN 
    -- FIXED: 'unique_name_category'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_name_category' AND conrelid = 'destinations'::regclass) THEN 
        ALTER TABLE destinations ADD CONSTRAINT unique_name_category UNIQUE (name, category);
    END IF; 
END $$;


INSERT INTO destinations (name, price, image, description, category)
VALUES (
    'Paris, France',
    128,
    '/images/Product-card-1.jpg',
    'Romantic escapes, art, and cafés.',
    'spring'
  ),
  (
    'Kyoto, Japan',
    190,
    '/images/Product-card-1.jpg',
    'Cherry blossoms and temples.',
    'spring'
  ),
  (
    'Santorini, Greece',
    225,
    '/images/Product-card-1.jpg',
    'Sunsets, sea views, and serenity.',
    'summer'
  ),
  (
    'Bali, Indonesia',
    26,
    '/images/Product-card-1.jpg',
    'Beaches, nature, and calm vibes.',
    'summer'
  ),
  (
    'Tuscany, Italy',
    160,
    '/images/Product-card-1.jpg',
    'Vineyards and golden hills.',
    'autumn'
  ),
  (
    'Swiss Alps',
    300,
    '/images/Product-card-1.jpg',
    'Skiing and snowy mountains.',
    'winter'
  ),
  (
    'Paris, France',
    128,
    '/images/Product-card-1.jpg',
    'Romantic escapes, art, and cafés.',
    'spring'
  ),
  (
    'Santorini, Greece',
    225,
    '/images/Product-card-1.jpg',
    'Sunsets, sea views, and serenity.',
    'spring'
  ),
  (
    'Bali, Indonesia',
    26,
    '/images/Product-card-1.jpg',
    'Beaches, nature, and calm vibes.',
    'spring'
  ),
  (
    'Kyoto, Japan',
    190,
    '/images/Product-card-1.jpg',
    'Cherry blossoms and temples.',
    'spring'
  ),
  (
    'Barcelona, Spain',
    110,
    '/images/Product-card-1.jpg',
    'Urban beaches and tapas nights.',
    'summer'
  ),
  (
    'Mykonos, Greece',
    128,
    '/images/Product-card-1.jpg',
    'Whitewashed alleys and seaside fun.',
    'summer'
  ),
  (
    'Nice, France',
    128,
    '/images/Product-card-1.jpg',
    'Pebbled beaches and coastal charm.',
    'summer'
  ),
  (
    'Amalfi Coast, Italy',
    128,
    '/images/Product-card-1.jpg',
    'Cliffside villas and lemon groves.',
    'summer'
  ),
  (
    'Tuscany, Italy',
    160,
    '/images/Product-card-1.jpg',
    'Vineyards, golden hills, and rustic villas.',
    'autumn'
  ),
  (
    'Prague, Czech',
    189,
    '/images/Product-card-1.jpg',
    'Cobblestone walks and cozy cafés.',
    'autumn'
  ),
  (
    'Seoul, South Korea',
    105,
    '/images/Product-card-1.jpg',
    'Autumn foliage and street food.',
    'autumn'
  ),
  (
    'Munich, Germany',
    115,
    '/images/Product-card-1.jpg',
    'Oktoberfest and beer gardens.',
    'autumn'
  ),
  (
    'Reykjavik, Iceland',
    128,
    '/images/Product-card-1.jpg',
    'Auroras, hot springs, and winter wonders.',
    'winter'
  ),
  (
    'Vienna, Austria',
    128,
    '/images/Product-card-1.jpg',
    'Christmas markets and snowy strolls.',
    'winter'
  ),
  (
    'Quebec City, Canada',
    128,
    '/images/Product-card-1.jpg',
    'Snowy magic, castles, and French flair.',
    'winter'
  ),
  (
    'Lucerne, Switzerland',
    128,
    '/images/Product-card-1.jpg',
    'Lakes, mountains, and old-town charm.',
    'winter'
  )
  ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS deals (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  location VARCHAR(150) NOT NULL,
  image TEXT NOT NULL,
  rating DECIMAL(2, 1),
  review_count INT,
  price_original INT,
  price_discount INT,
  tag TEXT DEFAULT 'Getaway Deal'
);

DO $$ 
BEGIN 
    -- FIXED: 'unique_name_category'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_title_location' AND conrelid = 'deals'::regclass) THEN 
        ALTER TABLE deals ADD CONSTRAINT unique_title_location UNIQUE (title, location);
    END IF; 
END $$;

INSERT INTO deals (
    title,
    location,
    image,
    rating,
    review_count,
    price_original,
    price_discount
  )
VALUES (
    'Seaside Serenity Villa',
    'Amalfi Coast, Italy',
    '/images/Product-card-1.jpg',
    4.8,
    118,
    250,
    175
  ),
  (
    'Tropical Bungalow',
    'Phuket, Thailand',
    '/images/Product-card-1.jpg',
    3.8,
    210,
    210,
    160
  ),
  (
    'Santorini Sunset Suites',
    'Santorini, Greece',
    '/images/Product-card-1.jpg',
    4.9,
    185,
    300,
    255
  ),
  (
    'Marbella Resort',
    'Marbella, Spain',
    '/images/Product-card-1.jpg',
    4.6,
    142,
    280,
    190
  ),
  (
    'Swiss Ski Chalet',
    'Zermatt, Switzerland',
    '/images/Product-card-1.jpg',
    4.9,
    300,
    400,
    320
  )
  ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS top_sights (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  flag_icon VARCHAR(10) NOT NULL,
  image TEXT NOT NULL
);

DO $$ 
BEGIN 
    -- FIXED: 'unique_name'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_sights_name' AND conrelid = 'top_sights'::regclass) THEN 
        ALTER TABLE top_sights ADD CONSTRAINT unique_sights_name UNIQUE (name);
    END IF; 
END $$;


INSERT INTO top_sights (name, flag_icon, image)
VALUES ('Sassnitz', 'FI', '/images/Top-Sight-1.jpg'),
  ('Binz', 'VN', '/images/Top-Sight-1.jpg'),
  ('Sagard', 'FR', '/images/Top-Sight-1.jpg'),
  ('Bergen', 'GB', '/images/Top-Sight-1.jpg'),
  ('Freedom', 'US', '/images/Top-Sight-1.jpg')
  ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS things_to_do (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  image TEXT NOT NULL,
  category VARCHAR(50) NOT NULL
);

DO $$ 
BEGIN 
    -- FIXED: 'unique_name'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_things_to_do_name' AND conrelid = 'things_to_do'::regclass) THEN 
        ALTER TABLE things_to_do ADD CONSTRAINT unique_things_to_do_name UNIQUE (name);
    END IF; 
END $$;

INSERT INTO things_to_do (name, image, category)
VALUES (
    'Sagrada Familia',
    '/images/Product-card-1.jpg',
    'explore'
  ),
  (
    'Park Güell',
    '/images/Product-card-1.jpg',
    'explore'
  ),
  (
    'Casa Milà',
    '/images/Product-card-1.jpg',
    'explore'
  ),
  (
    'Sacred Heart Temple',
    '/images/Product-card-1.jpg',
    'explore'
  ),
  (
    'Arc de Triomf',
    '/images/Product-card-1.jpg',
    'explore'
  ),
  (
    'Casa Batlló',
    '/images/Product-card-1.jpg',
    'explore'
  ),
  (
    'Barceloneta Beach',
    '/images/Product-card-1.jpg',
    'beach'
  ),
  (
    'Bogatell Beach',
    '/images/Product-card-1.jpg',
    'beach'
  ),
  (
    'Picasso Museum',
    '/images/Product-card-1.jpg',
    'museum'
  ),
  (
    'Magic Fountain',
    '/images/Product-card-1.jpg',
    'show'
  ),
  (
    'Paella Cooking Class',
    '/images/Product-card-1.jpg',
    'food'
  ),
  (
    'Opium Club',
    '/images/Product-card-1.jpg',
    'nightlife'
  )
  ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS home_Guests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  location VARCHAR(150) NOT NULL,
  image TEXT NOT NULL,
  rating DECIMAL(2, 1),
  review_count INT,
  price_original INT
);

DO $$ 
BEGIN 
    -- FIXED: 'unique_title_location'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_home_guests_title_location' AND conrelid = 'home_Guests'::regclass) THEN 
        ALTER TABLE home_Guests ADD CONSTRAINT unique_home_guests_title_location UNIQUE (title, location);
    END IF; 
END $$;

INSERT INTO home_Guests (
    title,
    location,
    image,
    rating,
    review_count,
    price_original
  )
VALUES (
    'Seaside Serenity Villa',
    'Amalfi Coast, Italy',
    '/images/Product-card-1.jpg',
    4.8,
    118,
    250
  ),
  (
    'Tropical Bungalow',
    'Phuket, Thailand',
    '/images/Product-card-1.jpg',
    3.8,
    210,
    210
  ),
  (
    'Santorini Sunset Suites',
    'Santorini, Greece',
    '/images/Product-card-1.jpg',
    4.9,
    185,
    300
  ),
  (
    'Marbella Resort',
    'Marbella, Spain',
    '/images/Product-card-1.jpg',
    4.6,
    142,
    280
  ),
  (
    'Swiss Ski Chalet',
    'Zermatt, Switzerland',
    '/images/Product-card-1.jpg',
    4.9,
    300,
    400
  )
  ON CONFLICT DO NOTHING;