-- 1. Session & Auth Tables
CREATE TABLE IF NOT EXISTS user_session (
  sid varchar NOT NULL COLLATE "default" PRIMARY KEY,
  sess json NOT NULL,
  expire timestamp(6) NOT NULL
) WITH (OIDS = FALSE);
CREATE INDEX IF NOT EXISTS IDX_user_session_expire ON user_session USING BTREE (expire);

CREATE TABLE IF NOT EXISTS employee_session (
  sid varchar NOT NULL COLLATE "default" PRIMARY KEY,
  sess json NOT NULL,
  expire timestamp(6) NOT NULL
) WITH (OIDS = FALSE);
CREATE INDEX IF NOT EXISTS IDX_employee_session_expire ON employee_session USING BTREE (expire);

CREATE TABLE IF NOT EXISTS passwordResetTokens (
  email VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL PRIMARY KEY,
  expiresAt TIMESTAMP NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. User & Employee Tables
CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(100) UNIQUE NOT NULL,
  salt bytea NOT NULL,
  hash bytea NOT NULL,
  email varchar(100) UNIQUE NOT NULL,
  firstName varchar(100) NOT NULL,
  lastName varchar(100),
  phoneNumber varchar(11),
  gender varchar(10) NOT NULL DEFAULT 'None',
  birthDate date,
  countryCode char(2) NOT NULL DEFAULT 'UN',
  address varchar(256),
  avatar text
);

CREATE TABLE IF NOT EXISTS employees (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(100) UNIQUE NOT NULL,
  avatar text,
  salt bytea NOT NULL,
  hash bytea NOT NULL,
  email varchar(100) UNIQUE NOT NULL,
  phone varchar(100) UNIQUE,
  branchID int,
  hotelID int,
  firstName varchar(100) NOT NULL,
  lastName varchar(100),
  salary int NOT NULL,
  createdAt timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS roles (
  name varchar(100) NOT NULL PRIMARY KEY,
  tier int NOT NULL
);

CREATE TABLE IF NOT EXISTS employee_roles (
  employeeID int,
  role varchar(100),
  PRIMARY KEY (employeeID, role)
);

-- 3. Hotel & Room Infrastructure
CREATE TABLE IF NOT EXISTS branch (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  managerID INT,
  name varchar(100) NOT NULL,
  location varchar(255) NOT NULL,
  description text
);

CREATE TABLE IF NOT EXISTS amenities (
  name varchar(100) PRIMARY KEY,
  icon text NOT NULL,
  category varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS policies (
  name varchar(100) PRIMARY KEY,
  icon text NOT NULL,
  category varchar(100) DEFAULT 'General',
  description text NOT NULL,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS beds (
  name varchar(100) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS hotels (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  classification INT NOT NULL DEFAULT 0 CHECK (classification >= 0 AND classification <= 5),
  branchID int,
  location varchar(255) NOT NULL,
  description text,
  contact_email varchar(100),
  contact_phone varchar(20)
);

CREATE TABLE IF NOT EXISTS roomTypes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotelID INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  size INT NOT NULL DEFAULT 100,
  capacity INT NOT NULL DEFAULT 1,
  base_price INT NOT NULL DEFAULT 100,
  description TEXT
);

CREATE TABLE IF NOT EXISTS rooms (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotelID int NOT NULL,
  name VARCHAR(100) NOT NULL,
  typeID int NOT NULL,
  note TEXT
);

-- 1. Master Bookings / Cart (Parent Table)
CREATE TABLE IF NOT EXISTS reserves (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userID INT NOT NULL,
  guestID INT,
  
  status VARCHAR(20) DEFAULT 'Pending',
  -- Master timestamps
  created_at TIMESTAMP NOT NULL DEFAULT (now()),
  updated_at TIMESTAMP DEFAULT (now())
);

-- 2. Reserved Rooms (Child Table)
CREATE TABLE IF NOT EXISTS reserved_room (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserveID INT NOT NULL,
  hotelID INT NOT NULL, 
  roomID INT NOT NULL,
  
  -- Hotel-Level Tracking & Status 
  confirmation_code VARCHAR(20) NOT NULL, 
  booking_status VARCHAR(20) DEFAULT 'Pending',
  payment_status VARCHAR(20) DEFAULT 'Unpaid', 
  
  -- Room-Level Logistics
  checkin_date DATE NOT NULL,
  checkout_date DATE NOT NULL,
  num_adults INT DEFAULT 1,
  num_children INT DEFAULT 0,
  
  -- Financial & Metadata
  final_price DECIMAL(12, 2) NOT NULL,
  special_requests TEXT,
  cancellation_deadline TIMESTAMP DEFAULT (now() + INTERVAL '24 hours'),
  
  created_at TIMESTAMP NOT NULL DEFAULT (now()),
  updated_at TIMESTAMP DEFAULT (now())
  
  -- FK constraint removed from here
);

CREATE TABLE IF NOT EXISTS guests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotelID INT NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(255) UNIQUE,
  phone VARCHAR(20) NOT NULL,
  id_card_number VARCHAR(50), -- Passport or National ID for check-in
  address TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS booking (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guestID INT NOT NULL,
    hotelID INT NOT NULL,
    reserveID INT, -- Links to the online 'reserves' table (NULL for walk-ins)
    
    -- The aggregate status of the entire booking
    -- Partial Checked-In: At least one is checked-in
    -- Checked-In: All are checked-in
    -- Partial Checked-Out: At least one is checked-out
    -- Stayed: All are checked-out
    -- Cancelled: All are cancelled
    booking_status VARCHAR(30) DEFAULT 'Confirmed', 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS booked_room (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookingID INT NOT NULL,
    roomID INT NOT NULL,
    
    -- Room-specific stay dates
    checkin_date DATE NOT NULL DEFAULT (CURRENT_DATE),
    checkout_date DATE NOT NULL DEFAULT (CURRENT_DATE + 5),
    
    -- Individual room status (Checked-In, Checked-Out, Cancelled, etc.)
    room_status VARCHAR(20) DEFAULT 'Reserved',
    room_price DECIMAL(12, 2),
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reviews (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userID int NOT NULL,
  roomID int NOT NULL,
  created_at timestamp NOT NULL DEFAULT (now()),
  rating INT NOT NULL DEFAULT 0 CHECK (rating >= 0 AND rating <= 5),
  description text NOT NULL,
  pros text,
  cons text,
  like_count int,
  response text
);

CREATE TABLE IF NOT EXISTS shifts (
  employeeID int,
  day date DEFAULT (CURRENT_DATE),
  startTime time NOT NULL,
  endTime time NOT NULL,
  PRIMARY KEY (employeeID, day)
);

CREATE TABLE IF NOT EXISTS services (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotelID int NOT NULL,
  type varchar(100) NOT NULL,
  name varchar(100) NOT NULL,
  description text,
  coverImage text,
  price int NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS works (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employeeID int NOT NULL,
  serviceID int NOT NULL,
  startTime timestamp NOT NULL,
  endTime timestamp NOT NULL
);

-- 5. Marketing & Content Tables
CREATE TABLE IF NOT EXISTS deals (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  location VARCHAR(150) NOT NULL,
  image TEXT NOT NULL,
  rating DECIMAL(2, 1),
  review_count INT,
  price_original INT,
  price_discount INT,
  tag TEXT DEFAULT 'Getaway Deal'
);

CREATE TABLE IF NOT EXISTS top_sights (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  flag_icon VARCHAR(10) NOT NULL,
  image TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS things_to_do (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  image TEXT NOT NULL,
  category VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS destinations (
  id int GENERATED by default as IDENTITY PRIMARY key,
  name varchar(100) not null,
  price int not null default 0,
  image text not null,
  description text,
  category varchar(50) not null
);

CREATE TABLE IF NOT EXISTS home_Guests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  location VARCHAR(150) NOT NULL,
  image TEXT NOT NULL,
  rating DECIMAL(2, 1),
  review_count INT,
  price_original INT
);

-- 6. Many-to-Many Join Tables
CREATE TABLE IF NOT EXISTS users_reserves (
  users_id int,
  reserves_userID int,
  PRIMARY KEY (users_id, reserves_userID)
);

CREATE TABLE IF NOT EXISTS rooms_reserves (
  rooms_id int,
  reserves_roomID int,
  PRIMARY KEY (rooms_id, reserves_roomID)
);

CREATE TABLE IF NOT EXISTS users_reviews (
  users_id int,
  reviews_userID int,
  PRIMARY KEY (users_id, reviews_userID)
);

CREATE TABLE IF NOT EXISTS rooms_reviews (
  rooms_id int,
  reviews_roomID int,
  PRIMARY KEY (rooms_id, reviews_roomID)
);

-- Hotel Relationship Tables
CREATE TABLE IF NOT EXISTS hotel_amenities (
  hotelID int NOT NULL,
  amenity_name varchar(100) NOT NULL,
  PRIMARY KEY (hotelID, amenity_name)
);

CREATE TABLE IF NOT EXISTS hotel_policies (
  hotelID int NOT NULL,
  policy_name varchar(100) NOT NULL,
  PRIMARY KEY (hotelID, policy_name)
);

CREATE TABLE IF NOT EXISTS hotel_beds (
  hotelID int NOT NULL,
  bed_name varchar(100) NOT NULL,
  PRIMARY KEY (hotelID, bed_name)
);

CREATE TABLE IF NOT EXISTS hotel_images (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotelID int NOT NULL references hotels(id) on delete cascade,
  image_path text not null,
  image_url text,
  isCover boolean default FALSE,
  sort_order int default 0,
  created_at timestamp default (now())
);

-- Room Relationship Tables
CREATE TABLE IF NOT EXISTS room_type_amenities (
  room_typeID int NOT NULL,
  amenity_name varchar(100) NOT NULL,
  PRIMARY KEY (room_typeID, amenity_name)
);

CREATE TABLE IF NOT EXISTS room_type_beds (
  room_typeID int NOT NULL,
  bed_name varchar(100) NOT NULL,
  bed_count int NOT NULL DEFAULT 1, -- e.g., 2 for "2 Twin Beds"
  PRIMARY KEY (room_typeID, bed_name)
);

CREATE TABLE IF NOT EXISTS room_type_images (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_typeID int NOT NULL,
  image_url text NOT NULL
);