
-- ==========================================
-- 1. Table Creations (Unchanged)
-- ==========================================

CREATE TABLE IF NOT EXISTS user_session (
  sid varchar NOT NULL COLLATE "default",
  sess json NOT NULL,
  expire timestamp(6) NOT NULL,
  CONSTRAINT user_session_pkey PRIMARY KEY (sid) NOT DEFERRABLE INITIALLY IMMEDIATE
) WITH (OIDS = FALSE);

CREATE INDEX IF NOT EXISTS IDX_user_session_expire ON user_session USING BTREE (expire);

CREATE TABLE IF NOT EXISTS employee_session (
  sid varchar NOT NULL COLLATE "default",
  sess json NOT NULL,
  expire timestamp(6) NOT NULL,
  CONSTRAINT employee_session_pkey PRIMARY KEY (sid) NOT DEFERRABLE INITIALLY IMMEDIATE
) WITH (OIDS = FALSE);

CREATE INDEX IF NOT EXISTS IDX_employee_session_expire ON employee_session USING BTREE (expire);


CREATE table if not exists passwordResetTokens (
  email VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL PRIMARY KEY,
  expiresAt TIMESTAMP NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(100) UNIQUE NOT NULL,
  salt bytea NOT NULL,
  hash bytea NOT NULL,
  email varchar(100) UNIQUE NOT NULL,
  firstName varchar(100) NOT NULL,
  lastName varchar(100),
  phoneNumber varchar(11),
  gender varchar(10) NOT NULL DEFAULT 'None',
  birthDate date,
  countryCode char(2) NOT NULL DEFAULT 'UN',
  address varchar(256),
  avatar text
);

CREATE TABLE IF NOT EXISTS reserves (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userID int UNIQUE NOT NULL,
  roomID int UNIQUE NOT NULL,
  created_at timestamp NOT NULL DEFAULT (now()),
  checkinDate date NOT NULL,
  checkoutDate date NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userID int UNIQUE NOT NULL,
  roomID int UNIQUE NOT NULL,
  created_at timestamp NOT NULL DEFAULT (now()),
  rating INT NOT NULL DEFAULT 0 CHECK (
    rating >= 0
    AND rating <= 5
  ),
  description text NOT NULL,
  pros text,
  cons text,
  like_count int,
  response text
);

CREATE TABLE IF NOT EXISTS amenities (
  name varchar(100) PRIMARY KEY,
  icon text NOT NULL,
  category varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS policies (
  name varchar(100) PRIMARY KEY,
  description text NOT NULL
);

CREATE TABLE IF NOT EXISTS hotels (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  classification INT NOT NULL DEFAULT 0 CHECK (
    classification >= 0
    AND classification <= 5
  ),
  location varchar(255) NOT NULL,
  description text,
  amenities amenities [],
  policies policies [],
  previewImages text []
);

CREATE TABLE IF NOT EXISTS branch (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  location varchar(255) NOT NULL,
  description text
);

CREATE TABLE IF NOT EXISTS beds (
  name varchar(100) PRIMARY KEY,
  count int NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS rooms (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotelID int UNIQUE NOT NULL,
  amenities amenities [],
  price int NOT NULL,
  size int NOT NULL,
  type text NOT NULL,
  beds beds [],
  capacity int NOT NULL DEFAULT 1,
  discount decimal NOT NULL DEFAULT 0,
  previewImages text [],
  description text
);

CREATE TABLE IF NOT EXISTS booking (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roomID int UNIQUE NOT NULL,
  firstName varchar(100) NOT NULL,
  lastName varchar(100),
  phone varchar(11) NOT NULL,
  checkinDate date NOT NULL DEFAULT (CURRENT_DATE),
  checkoutDate date NOT NULL DEFAULT (CURRENT_DATE + 5)
);

CREATE TABLE IF NOT EXISTS roles (
  name varchar(100) NOT NULL PRIMARY KEY,
  tier int NOT NULL
);

CREATE TABLE IF NOT EXISTS employees (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(100) UNIQUE NOT NULL,
  salt bytea NOT NULL,
  hash bytea NOT NULL,
  email varchar(100) UNIQUE NOT NULL,
  hotelID int,
  firstName varchar(100) NOT NULL,
  lastName varchar(100),
  salary int NOT NULL
);

CREATE TABLE IF NOT EXISTS shifts (
  employeeID int,
  day date DEFAULT (CURRENT_DATE),
  startTime time NOT NULL,
  endTime time NOT NULL,
  PRIMARY KEY (employeeID, day)
);

CREATE TABLE IF NOT EXISTS services (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(100) NOT NULL,
  name varchar(100) NOT NULL,
  description text,
  coverImage text,
  price int NOT NULL DEFAULT 0,
  quantity int NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS works (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employeeID int UNIQUE NOT NULL,
  serviceID int UNIQUE NOT NULL,
  startTime timestamp NOT NULL,
  endTime timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS deals (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  location VARCHAR(150) NOT NULL,
  image TEXT NOT NULL,
  rating DECIMAL(2, 1),
  review_count INT,
  price_original INT,
  price_discount INT,
  tag TEXT DEFAULT 'Getaway Deal'
);

CREATE TABLE IF NOT EXISTS top_sights (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  flag_icon VARCHAR(10) NOT NULL,
  image TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS things_to_do (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  image TEXT NOT NULL,
  category VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS destinations(
  id int GENERATED by default as IDENTITY PRIMARY key,
  name varchar(100) not null,
  price int not null default 0,
  image text not null,
  description text,
  category varchar(50) not null
);

CREATE TABLE IF NOT EXISTS home_Guests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  location VARCHAR(150) NOT NULL,
  image TEXT NOT NULL,
  rating DECIMAL(2, 1),
  review_count INT,
  price_original INT
);

-- Tables that depend on FKs created below
CREATE TABLE IF NOT EXISTS branch_hotels (
  branch_id int,
  hotel_id int,
  PRIMARY KEY (branch_id, hotel_id)
);

CREATE TABLE IF NOT EXISTS users_reserves (
  users_id int,
  reserves_userID int,
  PRIMARY KEY (users_id, reserves_userID)
);

CREATE TABLE IF NOT EXISTS rooms_reserves (
  rooms_id int,
  reserves_roomID int,
  PRIMARY KEY (rooms_id, reserves_roomID)
);

CREATE TABLE IF NOT EXISTS users_reviews (
  users_id int,
  reviews_userID int,
  PRIMARY KEY (users_id, reviews_userID)
);

CREATE TABLE IF NOT EXISTS rooms_reviews (
  rooms_id int,
  reviews_roomID int,
  PRIMARY KEY (rooms_id, reviews_roomID)
);

CREATE TABLE IF NOT EXISTS employee_roles (
  employeeID int,
  role varchar(100),
  PRIMARY KEY (employeeID, role)
);

-- ==========================================
-- 2. Alter Tables (Rewritten with DO Blocks)
-- ==========================================

-- 2. Link Branch_Hotels -> Hotels
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_branch_hotel' AND conrelid = 'branch_hotels'::regclass) THEN 
        ALTER TABLE branch_hotels ADD CONSTRAINT fk_branch_hotel FOREIGN KEY (hotel_id) REFERENCES hotels (id);
    END IF; 
END $$;

-- 3. Link Users_Reserves -> Users
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_id' AND conrelid = 'users_reserves'::regclass) THEN 
        ALTER TABLE users_reserves ADD CONSTRAINT fk_users_id FOREIGN KEY (users_id) REFERENCES users (id);
    END IF; 
END $$;

-- 4. Link Users_Reserves -> Reserves
DO $$ 
BEGIN 
    -- FIXED: 'fk_reserves_userid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_reserves_userid' AND conrelid = 'users_reserves'::regclass) THEN 
        ALTER TABLE users_reserves ADD CONSTRAINT fk_reserves_userID FOREIGN KEY (reserves_userID) REFERENCES reserves (userID);
    END IF; 
END $$;

-- 5. Link Rooms_Reserves -> Rooms
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rooms_id' AND conrelid = 'rooms_reserves'::regclass) THEN 
        ALTER TABLE rooms_reserves ADD CONSTRAINT fk_rooms_id FOREIGN KEY (rooms_id) REFERENCES rooms (id);
    END IF; 
END $$;

-- 6. Link Rooms_Reserves -> Reserves
DO $$ 
BEGIN 
    -- FIXED: 'fk_reserves_roomid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_reserves_roomid' AND conrelid = 'rooms_reserves'::regclass) THEN 
        ALTER TABLE rooms_reserves ADD CONSTRAINT fk_reserves_roomID FOREIGN KEY (reserves_roomID) REFERENCES reserves (roomID);
    END IF; 
END $$;

-- 7. Link Users_Reviews -> Users
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_id' AND conrelid = 'users_reviews'::regclass) THEN 
        ALTER TABLE users_reviews ADD CONSTRAINT fk_users_id FOREIGN KEY (users_id) REFERENCES users (id);
    END IF; 
END $$;

-- 8. Link Users_Reviews -> Reviews
DO $$ 
BEGIN 
    -- FIXED: 'fk_reviews_userid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_reviews_userid' AND conrelid = 'users_reviews'::regclass) THEN 
        ALTER TABLE users_reviews ADD CONSTRAINT fk_reviews_userID FOREIGN KEY (reviews_userID) REFERENCES reviews (userID);
    END IF; 
END $$;

-- 9. Link Rooms_Reviews -> Rooms
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rooms_id' AND conrelid = 'rooms_reviews'::regclass) THEN 
        ALTER TABLE rooms_reviews ADD CONSTRAINT fk_rooms_id FOREIGN KEY (rooms_id) REFERENCES rooms (id);
    END IF; 
END $$;

-- 10. Link Rooms_Reviews -> Reviews
DO $$ 
BEGIN 
    -- FIXED: 'fk_reviews_roomid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_reviews_roomid' AND conrelid = 'rooms_reviews'::regclass) THEN 
        ALTER TABLE rooms_reviews ADD CONSTRAINT fk_reviews_roomID FOREIGN KEY (reviews_roomID) REFERENCES reviews (roomID);
    END IF; 
END $$;

-- 11. Link Rooms -> Hotels
DO $$ 
BEGIN 
    -- FIXED: 'fk_hotelid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_hotelid' AND conrelid = 'rooms'::regclass) THEN 
        ALTER TABLE rooms ADD CONSTRAINT fk_hotelID FOREIGN KEY (hotelID) REFERENCES hotels (id);
    END IF; 
END $$;

-- 12. Link Booking -> Rooms
DO $$ 
BEGIN 
    -- FIXED: 'fk_roomid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_roomid' AND conrelid = 'booking'::regclass) THEN 
        ALTER TABLE booking ADD CONSTRAINT fk_roomID FOREIGN KEY (roomID) REFERENCES rooms (id);
    END IF; 
END $$;


-- 14. Link Shifts -> Employees
DO $$ 
BEGIN 
    -- FIXED: 'fk_employeeid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_employeeid' AND conrelid = 'shifts'::regclass) THEN 
        ALTER TABLE shifts ADD CONSTRAINT fk_employeeID FOREIGN KEY (employeeID) REFERENCES employees (id);
    END IF; 
END $$;

-- 15. Link Works -> Employees
DO $$ 
BEGIN 
    -- FIXED: 'fk_employeeid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_employeeid' AND conrelid = 'works'::regclass) THEN 
        ALTER TABLE works ADD CONSTRAINT fk_employeeID FOREIGN KEY (employeeID) REFERENCES employees (id);
    END IF; 
END $$;

-- 16. Link Works -> Services
DO $$ 
BEGIN 
    -- FIXED: 'fk_serviceid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_serviceid' AND conrelid = 'works'::regclass) THEN 
        ALTER TABLE works ADD CONSTRAINT fk_serviceID FOREIGN KEY (serviceID) REFERENCES services (id);
    END IF; 
END $$;

-- 17. Link Employees -> Hotels
DO $$ 
BEGIN 
    -- FIXED: 'fk_hotelid'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_hotelid' AND conrelid = 'employees'::regclass) THEN 
        ALTER TABLE employees ADD CONSTRAINT fk_hotelid FOREIGN KEY (hotelid) REFERENCES hotels (id);
    END IF; 
END $$;

-- 18. Link Employee -> Roles
DO $$ 
BEGIN 
    -- FIXED: 'fk_employee_roles'
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_employee_roles' AND conrelid = 'employee_roles'::regclass) THEN 
        ALTER TABLE employee_roles ADD CONSTRAINT fk_employee_roles FOREIGN KEY (role) REFERENCES roles (name);
    END IF; 
END $$;

-- ==========================================
-- 3. Role-level Security
-- ==========================================

-- Employees
ALTER TABLE IF EXISTS employees ENABLE ROW LEVEL SECURITY;